name: Api Technical Task CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/api.abdullajonov.uz/company-api
            git pull
            /usr/bin/php /usr/bin/composer && /usr/bin/php /usr/bin/composer update
            /usr/bin/php artisan migrate:fresh --seed
