name: Api Technical Task CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/api.abdullajonov.uz/company-api
            git pull
            /usr/bin/php /usr/bin/composer update --no-interaction --no-plugins --no-scripts
            /usr/bin/php /usr/bin/composer install --no-interaction --no-plugins --no-scripts
            /usr/bin/php artisan migrate
